### ISSUE TITLE
Failed to Build

### ISSUE THREAD

**Issue by Krankenkasse** [nplhse/cois#465]
```
$ /var/www/html/cois/node_modules/.bin/encore dev
Running webpack ...

node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at BulkUpdateDecorator.hashFactory (/var/www/html/cois/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.update (/var/www/html/cois/node_modules/webpack/lib/util/createHash.js:46:50)
    at OriginalSource.updateHash (/var/www/html/cois/node_modules/webpack/node_modules/webpack-sources/lib/OriginalSource.js:104:8)
    at NormalModule._initBuildHash (/var/www/html/cois/node_modules/webpack/lib/NormalModule.js:870:17)
    at handleParseResult (/var/www/html/cois/node_modules/webpack/lib/NormalModule.js:936:10)
    at /var/www/html/cois/node_modules/webpack/lib/NormalModule.js:1028:4
    at processResult (/var/www/html/cois/node_modules/webpack/lib/NormalModule.js:745:11)
    at /var/www/html/cois/node_modules/webpack/lib/NormalModule.js:809:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.0.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Script yarn encore dev handling the setup-frontend event returned with error code 1
Script @setup-frontend was called via setup
```

Any Ideas how i can fix that?

**Comment by nplhse** [comment]
Sorry, I've just noticed this Issue and could not reproduce it. Do you have any more informations for me? The build is (currently) working on all of my platforms, but in the past the "main" branch was kind of broken from time to time.
